# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-31 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_session', models.CharField(max_length=64)),
                ('openid', models.CharField(max_length=127)),
                ('active_time', models.DateTimeField()),
            ],
        ),
    ]
