# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-22 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courserecord',
            old_name='porcess',
            new_name='process',
        ),
    ]
