# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180122_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('available_time', models.DateTimeField()),
                ('course_name', models.CharField(max_length=127)),
            ],
        ),
    ]
